name: Main Pipeline

on:
  push:
    branches:
      - main
    paths:
      - '2-Tier-Deployment/Banking-app/**'
  workflow_dispatch:
    inputs:
      run_install:
        description: Install Docker + AWS CLI?
        type: boolean
        default: false
      run_health:
        description: Run health check?
        type: boolean
        default: true

jobs:
  test:
    uses: ./.github/workflows/test.yml
    permissions:
      id-token: write
      contents: read

  install:
    needs: test
    if: ${{ inputs.run_install == true }}
    uses: ./.github/workflows/tools_install.yml
    permissions:
      id-token: write
      contents: read

  health-before:
    needs: install
    if: |
      always() &&
      (needs.install.result == 'success' || needs.install.result == 'skipped')
    uses: ./.github/workflows/test_fleet.yml
    permissions:
      id-token: write
      contents: read

  # deploy:          ← commented out
  #   needs: health-before
  #   uses: ./.github/workflows/deploy.yml

  # health-after:    ← commented out
  #   needs: deploy
  #   uses: ./.github/workflows/test_fleet.yml