name: Main Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      run_health:
        description: Run health check?
        type: boolean
        default: true
      run_deploy:
        description: Run deployment?
        type: boolean
        default: true

jobs:
  test:
    uses: ./.github/workflows/test.yml
    permissions:
      id-token: write
      contents: read

  health-before:
    needs: test
    if: |
      always() &&
      (inputs.run_health == true || github.event_name == 'push')
    uses: ./.github/workflows/test_fleet.yml
    permissions:
      id-token: write
      contents: read

  deploy:
    needs: health-before
    if: |
      always() &&
      (inputs.run_deploy == true || github.event_name == 'push') &&
      (needs.health-before.result == 'success' || needs.health-before.result == 'skipped')
    uses: ./.github/workflows/deploy.yml
    permissions:
      id-token: write
      contents: read

  health-after:
    needs: deploy
    if: |
      always() &&
      needs.deploy.result == 'success'
    uses: ./.github/workflows/test_fleet.yml
    permissions:
      id-token: write
      contents: read