name: Setup Fleet

on:
  workflow_dispatch:
    inputs:
      run_install:
        description: Install Docker + AWS CLI on all fleet?
        type: boolean
        default: true

jobs:
  install:
    if: ${{ inputs.run_install == true }}
    uses: ./.github/workflows/tools_install.yml
    permissions:
      id-token: write
      contents: read